image: docker:git
services:
  - docker:dind

before_script:
  - docker info

build_image:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/
    - docker build -t registry.gitlab.com/kathra/kathra/kathra-services/kathra-synchromanager/kathra-synchromanager-java/kathra-users-synchronizer:latest .
    - docker push registry.gitlab.com/kathra/kathra/kathra-services/kathra-synchromanager/kathra-synchromanager-java/kathra-users-synchronizer:latest